# Generated by Django 4.1.2 on 2024-11-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('urls', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Songs',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
