# Generated by Django 4.1.2 on 2024-11-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_songs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='artist',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='urls',
            new_name='url',
        ),
        migrations.AddField(
            model_name='songs',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='lyrics',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
