# Generated by Django 4.1.2 on 2024-11-28 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_rename_artist_songs_author_rename_title_songs_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('lyrics', models.CharField(max_length=2000)),
                ('topics', models.CharField(max_length=100)),
                ('mp3_url', models.CharField(max_length=200)),
                ('cover_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favlists', models.ManyToManyField(related_name='user_favs', to='myapp.favlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.AddField(
            model_name='favlist',
            name='songs',
            field=models.ManyToManyField(related_name='favlists', to='myapp.song'),
        ),
    ]
